import type { User } from "@prisma/client"
import { prisma } from "@/lib/prisma"
import { resolveLocale, type AppLocale } from "@/lib/i18n"

const teamNameTemplates: Record<AppLocale, (name: string) => string> = {
  af: (name) => `${name} se span`,
  ak: (name) => `${name} kuw`,
  am: (name) => `የ${name} ቡድን`,
  ar: (name) => `فريق ${name}`,
  arz: (name) => `فريق ${name}`,
  as: (name) => `${name}ৰ দল`,
  az: (name) => `${name} komandası`,
  be: (name) => `Каманда ${name}`,
  bg: (name) => `Екипът на ${name}`,
  bn: (name) => `${name} এর দল`,
  bs: (name) => `${name} tim`,
  ca: (name) => `Equip de ${name}`,
  ceb: (name) => `Team ni ${name}`,
  cs: (name) => `Tým ${name}`,
  cy: (name) => `Tîm ${name}`,
  da: (name) => `${name}s team`,
  de: (name) => `Team von ${name}`,
  dv: (name) => `${name} ގެ ޓީމް`,
  el: (name) => `Ομάδα ${name}`,
  en: (name) => `${name}'s team`,
  es: (name) => `Equipo de ${name}`,
  "es-ES": (name) => `Equipo de ${name}`,
  et: (name) => `${name} tiim`,
  eu: (name) => `${name} taldea`,
  fa: (name) => `تیم ${name}`,
  fi: (name) => `${name}n tiimi`,
  fil: (name) => `Team ni ${name}`,
  "fil-PH": (name) => `Team ni ${name}`,
  fr: (name) => `Équipe de ${name}`,
  ga: (name) => `Foireann ${name}`,
  gd: (name) => `Sgioba ${name}`,
  gl: (name) => `Equipo de ${name}`,
  gu: (name) => `${name}ની ટીમ`,
  ha: (name) => `Ƙungiyar ${name}`,
  he: (name) => `הצוות של ${name}`,
  hi: (name) => `${name} की टीम`,
  hr: (name) => `${name} tim`,
  ht: (name) => `Ekip ${name}`,
  hu: (name) => `${name} csapata`,
  hy: (name) => `${name}-ի թիմը`,
  id: (name) => `Tim ${name}`,
  ig: (name) => `Otu ${name}`,
  is: (name) => `Teymi ${name}`,
  it: (name) => `Team di ${name}`,
  ja: (name) => `${name}のチーム`,
  jv: (name) => `Tim ${name}`,
  ka: (name) => `${name}-ის გუნდი`,
  "kk-KZ": (name) => `${name} командасы`,
  "km-KH": (name) => `ក្រុមរបស់ ${name}`,
  kn: (name) => `${name} ತಂಡ`,
  ko: (name) => `${name} 팀`,
  ku: (name) => `Tîma ${name}`,
  ky: (name) => `${name} командасы`,
  lb: (name) => `Team vum ${name}`,
  "lo-LA": (name) => `ທີມຂອງ ${name}`,
  lt: (name) => `${name} komanda`,
  lv: (name) => `${name} komanda`,
  mg: (name) => `Ekipa ${name}`,
  mi: (name) => `Tīma ${name}`,
  mk: (name) => `Тимот на ${name}`,
  ml: (name) => `${name}ന്റെ ടീം`,
  mn: (name) => `${name}-ийн баг`,
  mr: (name) => `${name}चा संघ`,
  ms: (name) => `Pasukan ${name}`,
  mt: (name) => `Tim ta' ${name}`,
  my: (name) => `${name}၏ အဖွဲ့`,
  nb: (name) => `${name}s team`,
  ne: (name) => `${name}को टोली`,
  nl: (name) => `Team van ${name}`,
  nn: (name) => `${name}s lag`,
  ny: (name) => `Gulu la ${name}`,
  om: (name) => `Garee ${name}`,
  or: (name) => `${name}ଙ୍କ ଦଳ`,
  pa: (name) => `${name} ਦੀ ਟੀਮ`,
  pl: (name) => `Zespół ${name}`,
  "pl-PL": (name) => `Zespół ${name}`,
  ps: (name) => `د ${name} ټیم`,
  pt: (name) => `Equipe de ${name}`,
  "pt-PT": (name) => `Equipa de ${name}`,
  ro: (name) => `Echipa lui ${name}`,
  ru: (name) => `Команда ${name}`,
  rw: (name) => `Ikipe ya ${name}`,
  si: (name) => `${name}ගේ කණ්ඩායම`,
  sk: (name) => `Tím ${name}`,
  sl: (name) => `Ekipa ${name}`,
  sn: (name) => `Chikwata cha ${name}`,
  so: (name) => `Kooxda ${name}`,
  sq: (name) => `Ekipi i ${name}`,
  sr: (name) => `Тим ${name}`,
  st: (name) => `Sehlopha sa ${name}`,
  sv: (name) => `${name}s team`,
  "sv-SE": (name) => `${name}s team`,
  sw: (name) => `Timu ya ${name}`,
  ta: (name) => `${name} குழு`,
  te: (name) => `${name} బృందం`,
  tg: (name) => `Дастаи ${name}`,
  th: (name) => `ทีมของ ${name}`,
  ti: (name) => `ጋንታ ${name}`,
  tk: (name) => `${name} topary`,
  tr: (name) => `${name} ekibi`,
  uk: (name) => `Команда ${name}`,
  ur: (name) => `${name} کی ٹیم`,
  uz: (name) => `${name} jamoasi`,
  vi: (name) => `Nhóm của ${name}`,
  xh: (name) => `Iqela lika-${name}`,
  yi: (name) => `${name}ס מאַנשאַפֿט`,
  yo: (name) => `Ẹgbẹ́ ${name}`,
  "zh-Hans": (name) => `${name}团队`,
  "zh-Hant": (name) => `${name}團隊`,
  "zh-HK": (name) => `${name}團隊`,
  zu: (name) => `Ithimba lika-${name}`,
  "zu-ZA": (name) => `Ithimba lika-${name}`,
}

function defaultTeamName(user: Pick<User, "email" | "userName" | "shortName">, locale?: AppLocale | string) {
  const name = user.userName?.trim() || user.shortName?.trim() || user.email?.split("@")[0] || "User"
  const resolved = resolveLocale(locale)
  return teamNameTemplates[resolved](name)
}

export async function createDefaultTeamIfNeeded(
  user: Pick<User, "id" | "email" | "userName" | "shortName">,
  locale?: AppLocale | string,
) {
  const now = new Date()
  const [membership, pendingInvite] = await Promise.all([
    prisma.teamMember.findFirst({
      where: { userID: user.id, team: { deletedAt: null } },
      select: { groupID: true },
    }),
    user.email
      ? prisma.teamEmailInvite.findFirst({
          where: {
            email: user.email,
            acceptedAt: null,
            OR: [{ expiresAt: null }, { expiresAt: { gt: now } }],
            team: { deletedAt: null },
          },
          select: { id: true },
        })
      : Promise.resolve(null),
  ])

  if (membership || pendingInvite) return null

  return prisma.team.create({
    data: {
      groupName: defaultTeamName(user, locale),
      ownerID: user.id,
      members: { create: { userID: user.id, role: "OWNER", roleID: 1 } },
    },
    select: { groupID: true },
  })
}
