import { resolveLocale } from "@/lib/i18n";
import type { TeamspaceTranslations } from "@/lib/teamspace/translations";
export const shareBaseCopy = {
  filters: ["筛选", "Filters", "篩選"],
  loadFailed: [
    "照片加载失败，已保留您的选择。",
    "Could not load photos. Your selection is saved.",
    "照片載入失敗，已保留您的選取。",
  ],
  retry: ["重试", "Retry", "重試"],
  selectionLimit: [
    "未能选择整天的照片，请缩小日期范围后重试。",
    "Could not select the whole day. Narrow the date range and retry.",
    "未能選取整天的照片，請縮小日期範圍後重試。",
  ],
  mapPage: [
    "地图显示当前页照片的位置，可翻页查看其他照片。",
    "The map shows locations for this page. Change pages to see more photos.",
    "地圖顯示目前頁面照片的位置，可翻頁查看其他照片。",
  ],

  more: ["加载更多", "Load more", "載入更多"],
  shared: [
    "通过 Timeprint 分享",
    "Shared with Timeprint",
    "透過 Timeprint 分享",
  ],
  project: ["项目", "Project", "專案"],
  member: ["成员", "Member", "成員"],
  team: ["团队", "Team", "團隊"],
  gallery: ["图库", "Gallery", "圖庫"],
  table: ["表格", "Table", "表格"],
  map: ["地图", "Map", "地圖"],
  search: [
    "搜索地点、成员、文件名",
    "Search location, member, filename",
    "搜尋地點、成員、檔案名稱",
  ],
  allProjects: ["所有项目", "All projects", "所有專案"],
  allMembers: ["所有成员", "All members", "所有成員"],
  dates: ["日期范围", "Date range", "日期範圍"],
  from: ["开始日期", "Start date", "開始日期"],
  to: ["结束日期", "End date", "結束日期"],
  type: ["全部类型", "All types", "全部類型"],
  photo: ["照片", "Photo", "照片"],
  video: ["视频", "Video", "影片"],
  newest: ["最新优先", "Newest first", "最新優先"],
  oldest: ["最早优先", "Oldest first", "最早優先"],
  clear: ["清除筛选", "Clear filters", "清除篩選"],
  select: ["选择", "Select", "選取"],
  selectAll: ["选择全部结果", "Select all results", "選取全部結果"],
  selected: ["已选择", "Selected", "已選取"],
  deselect: ["取消选择", "Clear selection", "取消選取"],
  download: ["下载照片", "Download photos", "下載照片"],
  excel: ["下载 Excel", "Download Excel", "下載 Excel"],
  pdf: ["打印 / PDF", "Print / PDF", "列印 / PDF"],
  link: ["复制链接", "Copy link", "複製連結"],
  copied: ["链接已复制", "Link copied", "連結已複製"],
  copyFailed: [
    "未能复制，请复制浏览器地址栏中的链接。",
    "Could not copy. Copy the link from your address bar.",
    "未能複製，請複製瀏覽器網址列中的連結。",
  ],
  noMatch: ["没有符合条件的照片", "No matching photos", "沒有符合條件的照片"],
  noMatchHint: [
    "试试其他日期或清除筛选。",
    "Try another date or clear the filters.",
    "試試其他日期或清除篩選。",
  ],
  count: ["张照片 / 视频", "photos / videos", "張照片 / 影片"],
  results: ["当前结果", "Results", "目前結果"],
  previous: ["上一页", "Previous page", "上一頁"],
  next: ["下一页", "Next page", "下一頁"],
  filename: ["文件名", "Filename", "檔案名稱"],
  time: ["拍摄时间", "Capture time", "拍攝時間"],
  location: ["地点", "Location", "地點"],
  noLocation: ["暂无地点", "No location", "暫無地點"],
  noMap: [
    "这些照片没有 GPS 坐标",
    "These photos have no GPS coordinates",
    "這些照片沒有 GPS 座標",
  ],
  mapError: [
    "地图底图未能加载，可从地点列表查看照片。",
    "Map tiles could not load. You can still open photos from the list.",
    "地圖底圖未能載入，可從地點列表查看照片。",
  ],
  missingGps: ["项未记录 GPS", "items without GPS", "項未記錄 GPS"],
  exportTitle: ["下载照片", "Download photos", "下載照片"],
  exportHint: [
    "照片将打包为 ZIP。单次最多 200 项，大文件请分批或单独下载。",
    "Photos are bundled in a ZIP. Download up to 200 items at a time; download large files separately.",
    "照片將打包為 ZIP。單次最多 200 項，大檔案請分批或單獨下載。",
  ],
  excelHint: [
    "每行一张照片，附项目、成员、拍摄时间、地点和查看链接。",
    "One photo per row, with project, member, capture time, location and a viewing link.",
    "每列一張照片，附專案、成員、拍攝時間、地點和查看連結。",
  ],
  excelImagesHint: ["每张缩略图不超过 90 KB，单次最多 200 项。图片无法加载时保留文字和查看链接。", "Each thumbnail is up to 90 KB. Export up to 200 items. If an image is unavailable, its details and viewing link are kept.", "每張縮圖不超過 90 KB，單次最多 200 項。圖片無法載入時保留文字和查看連結。"],
  excelFailed: ["Excel 未能生成，请重试。", "Excel could not be generated. Please try again.", "Excel 未能產生，請重試。"],
  exportBusy: ["其他下载正在准备中，请稍后重试。", "Other downloads are being prepared. Please try again shortly.", "其他下載正在準備中，請稍後重試。"],
  exportTimeout: ["准备下载超时，请重试。", "Preparing the download timed out. Please try again.", "準備下載逾時，請重試。"],
  excelViewPhotos: ["查看照片", "View photos", "查看照片"],
  excelViewOriginal: ["查看原图 / 视频", "View photo / video", "查看原圖 / 影片"],
  excelDate: ["日期", "Date", "日期"],
  excelTime: ["时间", "Time", "時間"],
  excelGPS: ["经纬度", "GPS coordinates", "經緯度"],
  excelTimezone: ["时区", "Timezone", "時區"],
  excelMediaType: ["类型", "Type", "類型"],
  excelVideoPreview: ["视频预览不可用，请点击查看链接", "Video preview unavailable. Open the viewing link.", "影片預覽無法使用，請點擊查看連結"],
  exportRange: ["下载范围", "Download scope", "下載範圍"],
  pageOnly: ["当前页", "Current page", "目前頁面"],
  allResults: ["全部筛选结果", "All filtered results", "全部篩選結果"],
  selectedOnly: ["已选照片", "Selected photos", "已選照片"],
  cancel: ["取消", "Cancel", "取消"],
  start: ["开始下载", "Start download", "開始下載"],
  busy: ["正在准备下载…", "Preparing download…", "正在準備下載…"],
  failed: [
    "下载失败，请重试或减少选择数量。",
    "Download failed. Try again or select fewer items.",
    "下載失敗，請重試或減少選取數量。",
  ],
  saved: [
    "文件已准备好，正在下载。",
    "File ready. Download starting.",
    "檔案已準備好，正在下載。",
  ],
  printHint: [
    "打印预览将包含当前导出范围，可选择“另存为 PDF”。",
    "The print preview uses your export scope. Choose “Save as PDF”.",
    "列印預覽會包含目前匯出範圍，可選擇「儲存為 PDF」。",
  ],
  print: ["打开打印预览", "Open print preview", "開啟列印預覽"],
  export: ["导出范围", "Export scope", "匯出範圍"],
  dateError: [
    "结束日期不能早于开始日期。",
    "End date must be on or after the start date.",
    "結束日期不能早於開始日期。",
  ],
  loading: ["正在加载…", "Loading…", "正在載入…"],
  photoFailed: ["图片未能加载", "Image unavailable", "圖片未能載入"],
  language: ["语言", "Language", "語言"],
  close: ["关闭", "Close", "關閉"],
} as const;
export function shareCopy(locale: string, translations?: TeamspaceTranslations) {
  const resolved = resolveLocale(locale || "en");
  const index = resolved === "zh-Hans" ? 0 : resolved === "zh-Hant" ? 2 : 1;
  return (key: keyof typeof shareBaseCopy) => translations?.s[key] ?? shareBaseCopy[key][index];
}
export type ShareCopy = ReturnType<typeof shareCopy>;
